const MembersInfo = [
    {
      id: 1,
      img: "/imgs/01.jpg",
      name: "Walter white",
      position: "Bryan Cranston",
      phone: "+93499459",
      email: "did.j@gmail.com",
      website: "milkd fij ",
    },
    {
      id: 2,
      img: "/imgs/02.jpg",
      name: "Skyler white",
      position: "Anna Gunn",
      phone: "+93499459",
      email: "did.j@gmail.com",
      website: "milkd fij ",
    },
    {
      id: 3,
      img: "/imgs/03.jpg",
      name: "Jesse Pinkman",
      position: "Aaron Paul",
      phone: "+93499459",
      email: "did.j@gmail.com",
      website: "milkd fij ",
    },
    {
      id: 4,
      img: "/imgs/04.jpg",
      name: "Saul Goodman",
      position: "Bob Odenkirk",
      phone: "+93499459",
      email: "did.j@gmail.com",
      website: "milkd fij ",
    },
    {
      id: 5,
      img: "/imgs/05.jpg",
      name: "Gus Fring",
      position: "Giancarlo Esposito",
      phone: "+93499459",
      email: "did.j@gmail.com",
      // website: "milkd fij ",
    },
    {
      id: 6,
      img: "/imgs/06.jpg",
      name: "Hank Schrader",
      position: "Dean Norris",
      phone: "+93499459",
      email: "did.j@gmail.com",
      website: "milkd fij ",
    },
    {
      id: 7,
      img: "/imgs/07.jpg",
      name: "link dii ",
      position: "jack open",
      phone: "+93499459",
      email: "did.j@gmail.com",
      website: "milkd fij ",
    },
    {
      id: 8,
      img: "/imgs/08.jpg",
      name: "pain ked",
      position: "jack close",
      phone: "+93499459",
      email: "did.j@gmail.com",
      // website: "milkd fij ",
    },
  ]

  export default MembersInfo;